// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qutnhnouocjcssxitzda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dG5obm91b2NqY3NzeGl0emRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTEyNDUsImV4cCI6MjA3MzE4NzI0NX0.tDw_VlPPYoIqYCeN5RBibXrR6Tza4ycspnU1dDUf1tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});